apiVersion: v2
name: rabbitmq
version: 1.0.0

dependencies:
  - name: rabbitmq
    version: 0.5.1
    repository: oci://ghcr.io/solidcharts/helm-charts # https://github.com/solidcharts/helm-charts/blob/main/charts
